language: ruby
rvm:
  - ruby-head
  - 2.6
  - 2.5
  - 2.4
  - jruby-head
gemfile:
  - gemfiles/Gemfile.activesupport-3.2.x
  - gemfiles/Gemfile.activesupport-4.2.x
  - gemfiles/Gemfile.activesupport-5.2.x
  - gemfiles/Gemfile.activesupport-edge
matrix:
  allow_failures:
    - gemfile: gemfiles/Gemfile.activesupport-edge
    - rvm: jruby-head
