language: ruby
rvm:
  - ruby-head
  - 2.2
  - 2.1
  - 2.0
  - jruby-head
gemfile:
  - gemfiles/Gemfile.activesupport-3.2.x
  - gemfiles/Gemfile.activesupport-4.0.x
  - gemfiles/Gemfile.activesupport-4.1.x
  - gemfiles/Gemfile.activesupport-edge
matrix:
  allow_failures:
    - gemfile: gemfiles/Gemfile.activesupport-edge
    - rvm: jruby-head
